//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArisCorpWeb.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;svg aria-hidden=&quot;true&quot; focusable=&quot;false&quot; data-prefix=&quot;fad&quot; data-icon=&quot;cat&quot; role=&quot;img&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; viewBox=&quot;0 0 512.363 512.363&quot; class=&quot;svg-inline--fa fa-cat fa-w-16 fa-9x&quot;&gt;
        ///  &lt;g class=&quot;fa-group&quot;&gt;
        ///    &lt;path fill=&quot;currentColor&quot; class=&quot;fa-secondary&quot; d=&quot;M255.52,445.61c-29.61,32.63-66.37,48.51-110.73,42.4-44.19-6.09-75-31.38-95-70.71,2.1-2.65,5.28-2.7,8-3.75l7.88-3c20,41.1,59,59.49,84.45,59.92V402.29a23.25,23.25,0,0,1,4.76,0c13.13,3,26.81-2.54,35.26-13.21a36.21,36.21,0,0,0,7.64-19.81c.7 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string alien_logo_svg {
            get {
                return ResourceManager.GetString("alien_logo_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;svg aria-hidden=&quot;true&quot; focusable=&quot;false&quot; data-prefix=&quot;fad&quot; data-icon=&quot;alien-monster&quot; role=&quot;img&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; viewBox=&quot;0 0 512 512&quot; height=&quot;50%&quot; style=&quot;margin-left: 0.5rem;&quot; class=&quot;svg-inline--fa fa-alien-monster fa-w-18 fa-9x&quot;&gt;
        ///  &lt;g class=&quot;fa-group&quot;&gt;
        ///    &lt;path fill=&quot;currentColor&quot; class=&quot;fa-secondary&quot; d=&quot;M279.25,511.81c-1.66-2.23-4.51-2.49-6.66-4-2.93-2-3.37-2.73-1.06-4.95a41.7,41.7,0,0,1,5-3.91c.36-.25,1.13,0,1.69.13s.86.54,1.27.52c.95-.05,2.57-.08,2.7-.49a5.7,5.7,0,0,0-.24-3.33c-.4 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string banu_head_svg {
            get {
                return ResourceManager.GetString("banu_head_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;svg aria-hidden=&quot;true&quot; focusable=&quot;false&quot; data-prefix=&quot;fad&quot; data-icon=&quot;alien-monster&quot; role=&quot;img&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; viewBox=&quot;0 0 512 512&quot; height=&quot;50%&quot; style=&quot;margin-left: 0.5rem;&quot; class=&quot;svg-inline--fa fa-alien-monster fa-w-18 fa-9x&quot;&gt;
        ///  &lt;g class=&quot;fa-group&quot;&gt;
        ///    &lt;path fill=&quot;currentColor&quot; class=&quot;fa-secondary&quot; d=&quot;M.19,265c2.91-.11,5.57,1.4,8.58,1.08,2.82-.29,5.46,1.33,8.17,1.73,1.91.28,3.9,1.13,6.19.36,1.93-.65,4.64-.93,6.24,1.52a.76.76,0,0,0,.33.25c2.75-2.62,5.46.16,8.19.16,1.81,0,.76-2.18,2 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string biestarium_head_svg {
            get {
                return ResourceManager.GetString("biestarium_head_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;svg class=&quot;img-gameplays&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; width=&quot;64&quot; height=&quot;64&quot; viewBox=&quot;0 0 832 978&quot;&gt;
        ///                &lt;image id=&quot;Back&quot; data-name=&quot;Ebene 1&quot; width=&quot;832&quot; height=&quot;978&quot; xlink:href=&quot;data:img/png;base64,iVBORw0KGgoAAAANSUhEUgAAA0AAAAPSCAYAAABSzboKAAAgAElEQVR4nOy9+bMc15Xn971bLlXvPRAbVxDc1dPgBkoiJUrdrXZ7elotqdXjsafbHo/9izvCjvCv/l/8gyP8g393hCOmNSO1RFECiZ3YFwIgsRHEQhDb22rJzHuv49ybWVUPeNgfgLecj3T5tqrMm5mFyvutc873CO8LMAzDMMwCI+rNefq2RIEe+hD1/xSkkUgqAeMBL3 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string gameplay_back {
            get {
                return ResourceManager.GetString("gameplay-back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;svg class=&quot;img-gameplays&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; width=&quot;140&quot; height=&quot;140&quot; viewBox=&quot;0 0 754 754&quot;&gt;
        ///                &lt;image id=&quot;Data Running&quot; data-name=&quot;Ebene 1&quot; width=&quot;754&quot; height=&quot;754&quot; xlink:href=&quot;data:img/png;base64,iVBORw0KGgoAAAANSUhEUgAAAvIAAALyCAYAAAC4mzBMAAAgAElEQVR4nOy9Cbhl11kduPbeZ7rDm6tejaoqlSTLkiXL8ijb8WzLU+OAOyEkmAAOIYG0CTQ0Y5MAAcyQhA8Iwf2RprtJoGPGBtwmqI0N8ic7QpY1T6XSUKWa33zfHc64d3//Hs495773SrI1S2dJt867555xn3PvWfvf618/U0qhQYMGDRq8sPB/ffLjzPM8 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string gameplay_datarunning {
            get {
                return ResourceManager.GetString("gameplay-datarunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;svg class=&quot;img-gameplays&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; width=&quot;140&quot; height=&quot;140&quot; viewBox=&quot;0 0 754 754&quot;&gt;
        ///                &lt;image id=&quot;Exploration&quot; width=&quot;754&quot; height=&quot;754&quot; xlink:href=&quot;data:img/png;base64,iVBORw0KGgoAAAANSUhEUgAAAvIAAALyCAYAAAC4mzBMAAAgAElEQVR4nOy9Cbhl11kduPbeZ7rDm6tejaoqlSTLkiXL8ijb8WzLU+OAOyEkmAAOIYG0CTQ0Y5MAAcyQhA8Iwf2RprtJoGPGBtwmqI0N8ic7QpY1T6XSUKWa33zfHc64d3//Hs495773SrI1S2dJt867555xn3PvWfvf618/U0qhQYMGDRq8sPB/ffLjzPM81uWb+znn/0wI4fu+D3p5n [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string gameplay_exploration {
            get {
                return ResourceManager.GetString("gameplay-exploration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;svg class=&quot;img-gameplays&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; width=&quot;140&quot; height=&quot;140&quot; viewBox=&quot;0 0 754 754&quot;&gt;
        ///                &lt;image id=&quot;Medical&quot; width=&quot;754&quot; height=&quot;754&quot; xlink:href=&quot;data:img/png;base64,iVBORw0KGgoAAAANSUhEUgAAAvIAAALyCAYAAAC4mzBMAAAgAElEQVR4nOy9Cbhl11kduPbeZ7rDm6tejaoqlSTLkiXL8ijb8WzLU+OAOyEkmAAOIYG0CTQ0Y5MAAcyQhA8Iwf2RprtJoGPGBtwmqI0N8ic7QpY1T6XSUKWa33zfHc64d3//Hs495773SrI1S2dJt867555xn3PvWfvf618/U0qhQYMGDRq8sPB/ffLjzPM81uWb+znn/0wI4fu+D3p5nkevj [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string gameplay_medical {
            get {
                return ResourceManager.GetString("gameplay-medical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;svg class=&quot;img-gameplays&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; width=&quot;140&quot; height=&quot;140&quot; viewBox=&quot;0 0 754 754&quot;&gt;
        ///                &lt;image id=&quot;Mining&quot; width=&quot;754&quot; height=&quot;754&quot; xlink:href=&quot;data:img/png;base64,iVBORw0KGgoAAAANSUhEUgAAAvIAAALyCAYAAAC4mzBMAAAgAElEQVR4nOy9Cbhl11kduPbeZ7rDm6tejaoqlSTLkiXL8ijb8WzLU+OAOyEkmAAOIYG0CTQ0Y5MAAcyQhA8Iwf2RprtJoGPGBtwmqI0N8ic7QpY1T6XSUKWa33zfHc64d3//Hs495773SrI1S2dJt867555xn3PvWfvf618/U0qhQYMGDRq8sPB/ffLjzPM81uWb+znn/0wI4fu+D3p5nkevjH [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string gameplay_mining {
            get {
                return ResourceManager.GetString("gameplay-mining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;svg class=&quot;img-gameplays&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; width=&quot;140&quot; height=&quot;140&quot; viewBox=&quot;0 0 754 754&quot;&gt;
        ///                &lt;image id=&quot;Refuel&quot; width=&quot;754&quot; height=&quot;754&quot; xlink:href=&quot;data:img/png;base64,iVBORw0KGgoAAAANSUhEUgAAAvIAAALyCAYAAAC4mzBMAAAgAElEQVR4nOy9Cbhl11kduPbeZ7rDm6tejaoqlSTLkiXL8ijb8WzLU+OAOyEkmAAOIYG0CTQ0Y5MAAcyQhA8Iwf2RprtJoGPGBtwmqI0N8ic7QpY1T6XSUKWa33zfHc64d3//Hs495773SrI1S2dJt867555xn3PvWfvf618/U0qhQYMGDRq8sPB/ffLjzPM81uWb+znn/0wI4fu+D3p5nkevjH [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string gameplay_refuel {
            get {
                return ResourceManager.GetString("gameplay-refuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;svg class=&quot;img-gameplays&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; width=&quot;140&quot; height=&quot;140&quot; viewBox=&quot;0 0 754 754&quot;&gt;
        ///                &lt;image id=&quot;Salvaging&quot; width=&quot;754&quot; height=&quot;754&quot; xlink:href=&quot;data:img/png;base64,iVBORw0KGgoAAAANSUhEUgAAAvIAAALyCAYAAAC4mzBMAAAgAElEQVR4nOy9Cbhl11kduPbeZ7rDm6tejaoqlSTLkiXL8ijb8WzLU+OAOyEkmAAOIYG0CTQ0Y5MAAcyQhA8Iwf2RprtJoGPGBtwmqI0N8ic7QpY1T6XSUKWa33zfHc64d3//Hs495773SrI1S2dJt867555xn3PvWfvf618/U0qhQYMGDRq8sPB/ffLjzPM81uWb+znn/0wI4fu+D3p5nke [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string gameplay_salvaging {
            get {
                return ResourceManager.GetString("gameplay-salvaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;svg class=&quot;img-gameplays&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; width=&quot;140&quot; height=&quot;140&quot; viewBox=&quot;0 0 754 754&quot;&gt;
        ///                &lt;image id=&quot;Science&quot; width=&quot;754&quot; height=&quot;754&quot; xlink:href=&quot;data:img/png;base64,iVBORw0KGgoAAAANSUhEUgAAAvIAAALyCAYAAAC4mzBMAAAgAElEQVR4nOy9Cbhl11kduPbeZ7rDm6tejaoqlSTLkiXL8ijb8WzLU+OAOyEkmAAOIYG0CTQ0Y5MAAcyQhA8Iwf2RprtJoGPGBtwmqI0N8ic7QpY1T6XSUKWa33zfHc64d3//Hs495773SrI1S2dJt867555xn3PvWfvf618/U0qhQYMGDRq8sPB/ffLjzPM81uWb+znn/0wI4fu+D3p5nkevj [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string gameplay_science {
            get {
                return ResourceManager.GetString("gameplay-science", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;svg class=&quot;img-gameplays&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; width=&quot;140&quot; height=&quot;140&quot; viewBox=&quot;0 0 754 754&quot;&gt;
        ///                &lt;image id=&quot;Security&quot; data-name=&quot;Defence__Combat (1)&quot; width=&quot;754&quot; height=&quot;754&quot; xlink:href=&quot;data:img/png;base64,iVBORw0KGgoAAAANSUhEUgAAAvIAAALyCAYAAAC4mzBMAAAgAElEQVR4nOy9B7ht11kdOuacq+16+jm36d6reyXL6s2SZQsbIyzZlgMJJhUMGJOQYJ4pgYT2QSABTMmXBBJKwnu893ghxNRn8GeDH9ggYhvhJlu9XOn208vuq875vn/OudYu5xxJtiRbZY2rrX323muvMtfae4//n+MfP1NKoUSJEiVKvLjwf7/v [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string gameplay_security {
            get {
                return ResourceManager.GetString("gameplay-security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;svg class=&quot;img-gameplays&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; width=&quot;140&quot; height=&quot;140&quot; viewBox=&quot;0 0 754 754&quot;&gt;
        ///                &lt;image id=&quot;Touring&quot; width=&quot;754&quot; height=&quot;754&quot; xlink:href=&quot;data:img/png;base64,iVBORw0KGgoAAAANSUhEUgAAAvIAAALyCAYAAAC4mzBMAAAgAElEQVR4nOy9Cbhl11kduPbeZ7rDm6tejaoqlSTLkiXL8ijb8WzLU+OAOyEkmAAOIYG0CTQ0Y5MAAcyQhA8Iwf2RprtJoGPGBtwmqI0N8ic7QpY1T6XSUKWa33zfHc64d3//Hs495773SrI1S2dJt867555xn3PvWfvf618/U0qhQYMGDRq8sPB/ffLjzPM81uWb+znn/0wI4fu+D3p5nkevj [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string gameplay_touring {
            get {
                return ResourceManager.GetString("gameplay-touring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;svg class=&quot;img-gameplays&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; width=&quot;140&quot; height=&quot;140&quot; viewBox=&quot;0 0 754 754&quot;&gt;
        ///                &lt;image id=&quot;Trading&quot; width=&quot;754&quot; height=&quot;754&quot; xlink:href=&quot;data:img/png;base64,iVBORw0KGgoAAAANSUhEUgAAAvIAAALyCAYAAAC4mzBMAAAgAElEQVR4nOy9Cbhl11kduPbeZ7rDm6tejaoqlSTLkiXL8ijb8WzLU+OAOyEkmAAOIYG0CTQ0Y5MAAcyQhA8Iwf2RprtJoGPGBtwmqI0N8ic7QpY1T6XSUKWa33zfHc64d3//Hs495773SrI1S2dJt867555xn3PvWfvf618/U0qhQYMGDRq8sPB/ffLjzPM81uWb+znn/0wI4fu+D3p5nkevj [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string gameplay_trading {
            get {
                return ResourceManager.GetString("gameplay-trading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;svg class=&quot;img-gameplays&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; width=&quot;140&quot; height=&quot;140&quot; viewBox=&quot;0 0 754 754&quot;&gt;
        ///                &lt;image id=&quot;Repair&quot; width=&quot;754&quot; height=&quot;754&quot; xlink:href=&quot;data:img/png;base64,iVBORw0KGgoAAAANSUhEUgAAAvIAAALyCAYAAAC4mzBMAAAgAElEQVR4nOy9Cbhl11kduPbeZ7rDm6tejaoqlSTLkiXL8ijb8WzLU+OAOyEkmAAOIYG0CTQ0Y5MAAcyQhA8Iwf2RprtJoGPGBtwmqI0N8ic7QpY1T6XSUKWa33zfHc64d3//Hs495773SrI1S2dJt867555xn3PvWfvf618/U0qhQYMGDRq8sPB/ffLjzPM81uWb+znn/0wI4fu+D3p5nkevjH [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string gamplay_repair {
            get {
                return ResourceManager.GetString("gamplay-repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;svg aria-hidden=&quot;true&quot;
        ///                     focusable=&quot;false&quot;
        ///                     data-prefix=&quot;fad&quot;
        ///                     data-icon=&quot;space-station-moon-alt&quot;
        ///                     role=&quot;img&quot;
        ///                     xmlns=&quot;http://www.w3.org/2000/svg&quot;
        ///                     viewBox=&quot;0 0 219.151 219.151&quot;
        ///                     class=&quot;svg-inline--fa fa-space-station-moon-alt fa-w-16 fa-5x&quot;&gt;
        ///                    &lt;g class=&quot;fa-group&quot;&gt;
        ///                        &lt;path fill=&quot;currentColor&quot;
        ///                              [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string nav_back_svg {
            get {
                return ResourceManager.GetString("nav_back_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;svg aria-hidden=&quot;true&quot;
        ///                     focusable=&quot;false&quot;
        ///                     data-prefix=&quot;fad&quot;
        ///                     data-icon=&quot;space-station-moon-alt&quot;
        ///                     role=&quot;img&quot;
        ///                     xmlns=&quot;http://www.w3.org/2000/svg&quot;
        ///                     viewBox=&quot;0 0 512 512&quot;
        ///                     height=&quot;512&quot;
        ///                     class=&quot;svg-inline--fa fa-space-station-moon-alt fa-w-16 fa-5x&quot;&gt;
        ///                    &lt;g class=&quot;fa-group&quot;&gt;
        ///                        &lt;path fill=&quot;currentColor&quot;
        ///   [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string nav_firma_svg {
            get {
                return ResourceManager.GetString("nav_firma_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;svg aria-hidden=&quot;true&quot;
        ///                     focusable=&quot;false&quot;
        ///                     data-prefix=&quot;fad&quot;
        ///                     data-icon=&quot;cat&quot;
        ///                     role=&quot;img&quot;
        ///                     xmlns=&quot;http://www.w3.org/2000/svg&quot;
        ///                     viewBox=&quot;0 0 512.363 512.363&quot;
        ///                     class=&quot;svg-inline--fa fa-cat fa-w-16 fa-9x&quot;&gt;
        ///                    &lt;g class=&quot;fa-group&quot;&gt;
        ///                        &lt;path fill=&quot;currentColor&quot;
        ///                              d=&quot;m439.581 72.204h24.832c10.084 0 18 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string nav_history_svg {
            get {
                return ResourceManager.GetString("nav_history_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;svg aria-hidden=&quot;true&quot;
        ///                     focusable=&quot;false&quot;
        ///                     data-prefix=&quot;fad&quot;
        ///                     data-icon=&quot;space-shuttle&quot;
        ///                     role=&quot;img&quot;
        ///                     xmlns=&quot;http://www.w3.org/2000/svg&quot;
        ///                     viewBox=&quot;0 0 512 512&quot;
        ///                     class=&quot;svg-inline--fa fa-space-shuttle fa-w-20 fa-5x&quot;&gt;
        ///                    &lt;g class=&quot;fa-group&quot;&gt;
        ///                        &lt;path fill=&quot;currentColor&quot;
        ///                              d=&quot;M166.07,291.13c0-2,0-2 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string nav_starmap_svg {
            get {
                return ResourceManager.GetString("nav_starmap_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;svg aria-hidden=&quot;true&quot;
        ///                     focusable=&quot;false&quot;
        ///                     data-prefix=&quot;fad&quot;
        ///                     data-icon=&quot;space-station-moon-alt&quot;
        ///                     role=&quot;img&quot;
        ///                     xmlns=&quot;http://www.w3.org/2000/svg&quot;
        ///                     viewBox=&quot;0 0 24 24&quot;
        ///                     class=&quot;svg-inline--fa fa-space-station-moon-alt fa-w-16 fa-5x&quot;&gt;
        ///                    &lt;g class=&quot;fa-group&quot;&gt;
        ///                        &lt;path fill=&quot;currentColor&quot;
        ///                              d=&quot;M8.75  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string nav_tech_svg {
            get {
                return ResourceManager.GetString("nav_tech_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;svg aria-hidden=&quot;true&quot; focusable=&quot;false&quot; data-prefix=&quot;fad&quot; data-icon=&quot;alien-monster&quot; role=&quot;img&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; viewBox=&quot;0 0 512 512&quot; height=&quot;50%&quot; style=&quot;margin-left: 0.5rem;&quot; class=&quot;svg-inline--fa fa-alien-monster fa-w-18 fa-9x&quot;&gt;
        ///  &lt;g class=&quot;fa-group&quot;&gt;
        ///    &lt;path fill=&quot;currentColor&quot; class=&quot;fa-primary&quot; d=&quot;M172.58,61V451.59c-9.67-5.07-18.78-9.29-27.32-14.45a199.89,199.89,0,0,1-44.86-36.75C89.12,388,78.93,374.77,71.06,359.9c-3.21-6-5.81-12.44-9.18-18.4-3.53-6.25-4.56-12.72-4.53-19.83q.28- [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string nav_uee_sub_svg {
            get {
                return ResourceManager.GetString("nav_uee_sub_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;svg aria-hidden=&quot;true&quot;
        ///                     focusable=&quot;false&quot;
        ///                     data-prefix=&quot;fad&quot;
        ///                     data-icon=&quot;space-station-moon-alt&quot;
        ///                     role=&quot;img&quot;
        ///                     xmlns=&quot;http://www.w3.org/2000/svg&quot;
        ///                     viewBox=&quot;0 0 512 512&quot;
        ///                     height=&quot;512&quot;
        ///                     class=&quot;svg-inline--fa fa-space-station-moon-alt fa-w-16 fa-5x&quot;&gt;
        ///                    &lt;g class=&quot;fa-group&quot;&gt;
        ///                            &lt;path fill=&quot;currentColor&quot; [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string nav_uee_svg {
            get {
                return ResourceManager.GetString("nav_uee_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die $(&apos;#image-map-pro-container&apos;).imageMapPro({&quot;id&quot;:2216,&quot;editor&quot;:{&quot;selected_shape&quot;:&quot;poly-6786&quot;,&quot;tool&quot;:&quot;select&quot;,&quot;shapeCounter&quot;:{&quot;polys&quot;:12}},&quot;general&quot;:{&quot;name&quot;:&quot;Untitled&quot;,&quot;shortcode&quot;:&quot;Technologie2&quot;,&quot;width&quot;:1825,&quot;height&quot;:635,&quot;naturalWidth&quot;:1825,&quot;naturalHeight&quot;:635},&quot;image&quot;:{&quot;url&quot;:&quot;/assets/img/exkurs/util/Schwerreck2.png&quot;},&quot;spots&quot;:[{&quot;id&quot;:&quot;poly-2867&quot;,&quot;title&quot;:&quot;Triebwerke Mount&quot;,&quot;type&quot;:&quot;poly&quot;,&quot;x&quot;:6.119,&quot;y&quot;:38.374,&quot;width&quot;:2.053,&quot;height&quot;:11.447,&quot;x_image_background&quot;:6.146637265711136,&quot;y_image_background&quot;:38.413699984373 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string schwerregJS {
            get {
                return ResourceManager.GetString("schwerregJS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die $(&apos;#image-map-pro-container&apos;).imageMapPro({&quot;id&quot;:1261,&quot;editor&quot;:{&quot;selected_shape&quot;:&quot;poly-4099&quot;,&quot;tool&quot;:&quot;select&quot;,&quot;zoom&quot;:8,&quot;shapeCounter&quot;:{&quot;rects&quot;:1,&quot;ovals&quot;:1,&quot;polys&quot;:2}},&quot;general&quot;:{&quot;name&quot;:&quot;Untitled&quot;,&quot;width&quot;:1200,&quot;height&quot;:841,&quot;naturalWidth&quot;:1200,&quot;naturalHeight&quot;:841},&quot;image&quot;:{&quot;url&quot;:&quot;/assets/img/exkurs/util/Starmap.webp&quot;},&quot;fullscreen&quot;:{&quot;start_in_fullscreen_mode&quot;:1},&quot;shapes&quot;:{&quot;glowing_shapes&quot;:1,&quot;glowing_shapes_color&quot;:&quot;#428bca&quot;,&quot;glow_opacity&quot;:0.25555555555555554,&quot;stop_glowing_on_mouseover&quot;:0},&quot;tooltips&quot;:{&quot;tooltip_ani [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string starmapJS {
            get {
                return ResourceManager.GetString("starmapJS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;svg aria-hidden=&quot;true&quot; focusable=&quot;false&quot; data-prefix=&quot;fad&quot; data-icon=&quot;alien-monster&quot; role=&quot;img&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; viewBox=&quot;0 0 512 512&quot; height=&quot;50%&quot; style=&quot;margin-left: 0.5rem;&quot; class=&quot;svg-inline--fa fa-alien-monster fa-w-18 fa-9x&quot;&gt;
        ///  &lt;g class=&quot;fa-group&quot;&gt;
        ///    &lt;path fill=&quot;currentColor&quot; class=&quot;fa-secondary&quot; d=&quot;M325,291.51c-13.33,12.65-13.44,11.95-13.31,11.3.9-4.29-1.59-7.41-3.74-10.59-1.5-2.22-4.16-2.86-6.46-3.86-2.46-1.08-3.81-2.82-5.12-5.14-1.42-2.53-.65-4.28.72-6.05a18.79,18.79,0,0,1,6- [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string tevarin_head_svg {
            get {
                return ResourceManager.GetString("tevarin_head_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;svg aria-hidden=&quot;true&quot; focusable=&quot;false&quot; data-prefix=&quot;fad&quot; data-icon=&quot;alien-monster&quot; role=&quot;img&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; viewBox=&quot;0 0 512 512&quot; height=&quot;50%&quot; style=&quot;margin-left: 0.5rem;&quot; class=&quot;svg-inline--fa fa-alien-monster fa-w-18 fa-9x&quot;&gt;
        ///  &lt;g class=&quot;fa-group&quot;&gt;
        ///    &lt;path fill=&quot;currentColor&quot; class=&quot;fa-secondary&quot; d=&quot;M-.1,234.31H.41c1.42-.13,3,.51,4.13-1,1.07,1.08,2.11,2.2,3.24,3.22A2.55,2.55,0,0,0,12,236c.33-.52.44-1.17.74-1.72,1.55-2.91,2.9-3.73,5.76-2.92,1.19.34,2.41,1.7,3.5.63a7.12,7.12,0,0,0 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string vanduul_head_svg {
            get {
                return ResourceManager.GetString("vanduul_head_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;svg aria-hidden=&quot;true&quot; focusable=&quot;false&quot; data-prefix=&quot;fad&quot; data-icon=&quot;alien-monster&quot; role=&quot;img&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; viewBox=&quot;0 0 512 512&quot; height=&quot;50%&quot; style=&quot;margin-left: 0.5rem;&quot; class=&quot;svg-inline--fa fa-alien-monster fa-w-18 fa-9x&quot;&gt;
        ///  &lt;g class=&quot;fa-group&quot;&gt;
        ///    &lt;path fill=&quot;currentColor&quot; class=&quot;fa-secondary&quot; d=&quot;M218.31,215.1c4-.12,4-.12,7.83-2.16,4,2.41,8.43,4.33,9.93,9.45-2,2-3.71-.25-5.33-.57-4.4-.86-12.62-1.34-16.18.24a27.7,27.7,0,0,0-4.56,3.15,46,46,0,0,0,.05,5.3,29.19,29.19,0,0,0,1.27, [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string xian_head_svg {
            get {
                return ResourceManager.GetString("xian_head_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        public static byte[] xiansvg {
            get {
                object obj = ResourceManager.GetObject("xiansvg", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
