// <auto-generated />
using ArisCorpWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ArisCorpWeb.Migrations
{
    [DbContext(typeof(AlienrassenContext))]
    [Migration("20210319223737_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ArisCorpWeb.Models.Alienrassen", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Besuch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diplomatie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Einleitung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Geschichte")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Heimatwelt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kriminalitat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kultur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Militar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureBesuch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureDiplomatie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureEinleitung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureGeschichte")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureHeimatwelt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureKriminalitat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureKultur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureMilitar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PicturePolitik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureReligion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureSicherheit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureSprache")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Politik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rasse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Religion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sicherheit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sprache")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Alienrassen");
                });
#pragma warning restore 612, 618
        }
    }
}
